services:
  - type: web
    name: doctor-appointment-backend
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt --only-binary=:all:
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
